EXPORT File_pregao_encerrado_2019 := MODULE
 EXPORT Layout := RECORD
 STRING	OC {XPATH('OC')};
 STRING UNIDADE_COMPRADORA {XPATH('UNIDADE_COMPRADORA')};
 STRING PROCEDIMENTO {XPATH('PROCEDIMENTO')};
 STRING SITUACAO {XPATH('SITUACAO')};
 STRING DT_ENCERRAMENTO {XPATH('DT_ENCERRAMENTO')};
 STRING LINK_EDITAL {XPATH('LINK_EDITAL')};
  
END;

 EXPORT File:= DATASET('~IC::LF::pregao_2019',Layout,JSON('/'));
END;
