IMPORT $;
IPTU := $.File_IPTU2019.Years;
ter :=IPTU.TIPO_DE_PADRAO_DA_CONSTRUCAO = ('TERRENO');
// sortedIPTU := SORT(ter, NOME_DE_LOGRADOURO_DO_IMOVEL,NUMERO_DO_IMOVEL);
// dedupdono := DEDUP(sortedIPTU,LEFT.NOME_DO_CONTRIBUINTE_1 = RIGHT.NOME_DO_CONTRIBUINTE_1);

EXPORT FIle_sdIPTU := ter;