IMPORT $;
IPTU := $.File_IPTU2019.Years;

sortedIPTU := SORT(IPTU, NOME_DE_LOGRADOURO_DO_IMOVEL,NUMERO_DO_IMOVEL);
dedupdono := DEDUP(sortedIPTU,LEFT.NOME_DO_CONTRIBUINTE_1 = RIGHT.NOME_DO_CONTRIBUINTE_1);

EXPORT IPTUterd := dedupdono;